config/routes.rb
Project::Application.routes.draw do
   resources :users
   resources :tracks

root to: 'users#index'

get '/login' => 'sessions#login'
post '/login' => 'sessions#create'
get '/signup' => 'users#new'
get '/logout' => 'sessions#logout'

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/track.rb
class Track < ActiveRecord::Base

	has_attached_file :clip
  belongs_to :user

  # validates_attachment_content_type :clip, :content_type => "audio/mpeg"
  # validates_attachment_file_name :clip, :matches => /.+\.mp3/
  do_not_validate_attachment_file_type :clip
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tracks

  validates :password_digest, :presence => true, :length => { :minimum => 6 }
  validates :email, :uniqueness => true #:format => /.+@.+\..+/ # imperfect, but okay
  validates :username, :presence => true




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user.authenticate(params[:session][:password])
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      redirect_to root_path 
    end
  end

  def logout
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tracks_controller.rb
class TracksController < ActionController::Base


	def create
		@track = Track.new(track_params)
		if @track.save
			@track.url = @track.clip.url.to_s
			@track.save
			 redirect_to root_path
		else
			# render 'new'
		end
	end

	def show
	end

	def track_params
		params.require(:track).permit(:clip, :title, :description, :longitude, :latitude)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user].permit(:username, :password, :password_confirmation, :email))
    @user.save!
    redirect_to root_path
  end

  def show
    @user = User.find(session[:current_user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="nav-links">
  <ul>
    <li><%= link_to "SoundMap", root_path, :id => 'logo' %></li>
    <% if session[:current_user_id] %>
      <li id="logout"><%= link_to "Sign Out", logout_path %></li>
      <li id="profile_link">Welcome, <%=User.find(session[:current_user_id]).username.capitalize%></li>
    <%else%>
      <li><a href="#" id="signup">Sign Up</a></li>
      <li><a href="#" id="signin">Sign In</a></li>
    <%end%>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundMap</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgR5AK13N6RoESZzQTkayssSuIbwhwayM&sensor=true">
  </script>
  <link href='http://fonts.googleapis.com/css?family=Kavoon' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Averia+Libre' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/tracks/_new.html.erb
  <%= form_for(:track, url: '/tracks') do |f| %>
    <p><%= f.text_field :title, placeholder: 'Title' %></p>
    <p><%= f.text_field :description, placeholder: 'Description'  %></p>
    <p><%= f.file_field :clip %></p>
    <input id='lon' type='hidden' name='track[longitude]' value=''></input>
    <input id='lat' type='hidden' name='track[latitude]' value=''></input>
    <p><%= f.submit 'Map It!' %></p>
  <% end %>
  <%= @longitude %>

app/views/tracks/new.html.erb
<%= form_for :track, url: tracks_path do |f| %>
	<p><%= f.text_field :title, placeholder: 'Title' %></p>
	<p><%= f.text_field :description, placeholder: 'Description'  %></p>
	<p><%= f.file_field :clip %></p>
	<p><%= f.submit 'Map It!' %></p>
<% end %>

app/views/users/_new.html.erb
  <h1>Sign Up</h1>
  <%= form_for :user do |f| %>
  <p><%= f.text_field :email, :placeholder => 'Email' %></p>
  <p><%= f.text_field :username, :placeholder => 'Username' %></p>
  <p>
    <%= f.password_field :password, :placeholder => 'Password' %><br>
    <%= f.password_field :password_confirmation, :placeholder => 'Confirmation' %>
  </p>
  <%= f.submit 'Sign Up' %>
  <% end %>

app/views/users/index.html.erb
<%= javascript_tag do %>
  window.tracks = <%=raw Track.all.to_json %>
<% end %>

<% if session[:current_user_id] %>
  <%= javascript_tag do %>
    window.user_tracks = <%=raw User.find(session[:current_user_id]).tracks.to_json %>
  <% end %>
<% else %>
  <%= javascript_tag do %>
    window.user_tracks = <%= {}.to_json %>
  <% end %>
<% end %>

<div id="map-canvas"></div>

<div id='footer'>
  <form id='geocoder'>
    <input id='geocode_bar' id='address' type='textbox' name='location' value='351 W. Hubbard Chicago, IL'>
    <input type='submit' value='Find Location' class="button">
  </form>

  <span id='song'>
    <audio id='player' controls></audio>
  </span>

  <button class="button" id='toggle_markers'>Toggle All Markers</button>
  <% if session[:current_user_id] %>
    <button class="button" id='toggle_user_markers'>Toggle User Markers</button>
  <% end %>
</div>


<div id="overlay"></div>


<div id="login_modal">
  <%= render '/sessions/login' %>
</div>

<div id="signup_modal">
  <%= render '/users/new' %>
</div>

<div id="audio_modal">
  <%= render '/tracks/new' %>
</div>